GET http://localhost:3000/api/books

###
GET http://localhost:3000/api/books/1

###
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "id": 2,
    "title": "Pelle kanin",
    "author": "Pär",
    "year": 1955
}

###
DELETE http://localhost:3000/api/books/2