GET http://localhost:3000/api/books

###
GET http://localhost:3000/api/books/0

###
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "title": "Pelle kanin 2",
    "author": "Pär",
    "year": 1980
}

###
PUT http://localhost:3000/api/books/1
Content-Type: application/json

{
    "id": 1,
    "title": "boken 2",
    "author": "Johanna",
    "year": 1984
}

###
DELETE http://localhost:3000/api/books/2